export const posts = [
  {
    title: "First Post",
    description: "First post description",
    date: "2026-01-15T00:00:00.000Z",
    published: true,
    featured: true,
    categories: ["programming"],
    tags: ["typescript", "react"],
    filePath: "posts/en/first-post",
    metadata: { readingTime: 3, wordCount: 500 },
    content: "<p>First post content</p>",
    body: "",
    locale: "en",
    slugName: "first-post",
    year: "2026",
    month: "01",
    day: "15",
    permalink: "/en/blog/2026/01/15/first-post",
  },
  {
    title: "Second Post",
    description: "Second post description",
    date: "2026-02-10T00:00:00.000Z",
    published: true,
    featured: false,
    categories: ["programming"],
    tags: ["docker", "container"],
    filePath: "posts/en/second-post",
    metadata: { readingTime: 5, wordCount: 800 },
    content: "<p>Second post content</p>",
    body: "",
    locale: "en",
    slugName: "second-post",
    year: "2026",
    month: "02",
    day: "10",
    permalink: "/en/blog/2026/02/10/second-post",
  },
  {
    title: "日本語の記事",
    description: "日本語の記事の説明",
    date: "2026-02-20T00:00:00.000Z",
    published: true,
    featured: true,
    categories: ["programming"],
    tags: ["nextjs", "react"],
    filePath: "posts/ja/japanese-post",
    metadata: { readingTime: 2, wordCount: 300 },
    content: "<p>日本語のコンテンツ</p>",
    body: "",
    locale: "ja",
    slugName: "japanese-post",
    year: "2026",
    month: "02",
    day: "20",
    permalink: "/ja/blog/2026/02/20/japanese-post",
  },
  {
    title: "Unrelated Post",
    description: "A post with no shared categories or tags",
    date: "2026-01-10T00:00:00.000Z",
    published: true,
    featured: false,
    categories: ["devops"],
    tags: ["kubernetes"],
    filePath: "posts/en/unrelated-post",
    metadata: { readingTime: 2, wordCount: 200 },
    content: "<p>Unrelated content</p>",
    body: "",
    locale: "en",
    slugName: "unrelated-post",
    year: "2026",
    month: "01",
    day: "10",
    permalink: "/en/blog/2026/01/10/unrelated-post",
  },
  {
    title: "Draft Post",
    description: "This is a draft",
    date: "2026-03-01T00:00:00.000Z",
    published: false,
    featured: true,
    categories: ["programming"],
    tags: ["draft"],
    filePath: "posts/en/draft-post",
    metadata: { readingTime: 1, wordCount: 100 },
    content: "<p>Draft content</p>",
    body: "",
    locale: "en",
    slugName: "draft-post",
    year: "2026",
    month: "03",
    day: "01",
    permalink: "/en/blog/2026/03/01/draft-post",
  },
];

export const categories = [
  {
    name: "Programming",
    slug: "programming",
    description: "Articles about programming",
    nameJa: "プログラミング",
    descriptionJa: "プログラミングに関する記事",
  },
];

export const pages = [
  {
    title: "About",
    description: "About shinyaz",
    filePath: "pages/en/about",
    body: "",
    locale: "en",
    slugName: "about",
    permalink: "/en/about",
  },
  {
    title: "About",
    description: "shinyaz について",
    filePath: "pages/ja/about",
    body: "",
    locale: "ja",
    slugName: "about",
    permalink: "/ja/about",
  },
];

export const tils = [
  {
    title: "TIL: Next.js use cache directive",
    description: "The use cache directive enables component-level caching",
    date: "2026-03-07T00:00:00.000Z",
    published: true,
    tags: ["nextjs", "caching"],
    filePath: "tils/en/nextjs-use-cache-directive",
    metadata: { readingTime: 1, wordCount: 80 },
    content: "<p>TIL content</p>",
    body: "",
    locale: "en",
    slugName: "nextjs-use-cache-directive",
    year: "2026",
    month: "03",
    day: "07",
    permalink: "/en/til/2026/03/07/nextjs-use-cache-directive",
  },
  {
    title: "TIL: Next.js の use cache ディレクティブ",
    description: "use cache ディレクティブでコンポーネントレベルのキャッシュが可能",
    date: "2026-03-07T00:00:00.000Z",
    published: true,
    tags: ["nextjs", "caching"],
    filePath: "tils/ja/nextjs-use-cache-directive",
    metadata: { readingTime: 1, wordCount: 80 },
    content: "<p>TIL コンテンツ</p>",
    body: "",
    locale: "ja",
    slugName: "nextjs-use-cache-directive",
    year: "2026",
    month: "03",
    day: "07",
    permalink: "/ja/til/2026/03/07/nextjs-use-cache-directive",
  },
  {
    title: "TIL: Draft TIL",
    description: "This is a draft TIL",
    date: "2026-03-06T00:00:00.000Z",
    published: false,
    tags: ["draft"],
    filePath: "tils/en/draft-til",
    metadata: { readingTime: 1, wordCount: 50 },
    content: "<p>Draft content</p>",
    body: "",
    locale: "en",
    slugName: "draft-til",
    year: "2026",
    month: "03",
    day: "06",
    permalink: "/en/til/2026/03/06/draft-til",
  },
];

export const projects = [
  {
    name: "@shinyaz",
    slug: "shinyaz-com",
    description: "Personal tech blog built with Next.js.",
    nameJa: "@shinyaz",
    descriptionJa: "Next.jsで構築した個人技術ブログ。",
    url: "https://shinyaz.com",
    github: "https://github.com/shinyaz/shinyaz.com",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS"],
    featured: true,
    order: 1,
  },
  {
    name: "ML Pipeline Orchestrator",
    slug: "sample-project",
    description: "A serverless ML pipeline orchestration framework.",
    nameJa: "ML パイプラインオーケストレーター",
    descriptionJa: "サーバーレス ML パイプライン基盤。",
    github: "https://github.com/shinyaz/ml-pipeline-orchestrator",
    techStack: ["Python", "AWS CDK", "Step Functions"],
    featured: true,
    order: 2,
  },
];

export const series = [
  { name: "Test Series", slug: "test-series", nameJa: "テストシリーズ" },
];
